### ISSUE TITLE
`Before=network.target` is insufficient

### ISSUE THREAD

**Issue by popsUlfr** [graysky2/odroid-auto-bridge#1]
Hi,

I was messing with my old odroid-c1 lately and bridging. But the service always starts after systemd-networkd.service which leaves the network configuration broken.

I added an override for `odroid-auto-bridge.service` :
```
Before=network.target systemd-networkd.service
```
To make sure it is started before systemd-networkd. Maybe installing it into `network-pre.target` might be better though.

**Comment by graysky2** [comment]
Odd, I cannot reproduce this on my C2 which is using systemd-networkd... it just works as-is.

When I look at `/usr/lib/systemd/system/systemd-networkd.service`:
```
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Wants=network.target
```

I agree with your thinking that changing the `Before` line to hit `network-pre.target` would be a more general solution.

Would you please try https://github.com/graysky2/odroid-auto-bridge/commit/1db87cd20e9ea7a4766f582ba3a678a33f34757d from the dev branch and see if it fixes this on your hardware?  I am using it on my C2 without errors.

**Comment by popsUlfr** [comment]
The commit didn't work :(

The following patch to the service works, it also makes more sense to install it into the network.target.
`Before=network-pre.target`, `Wants=network-pre.target` and `WantedBy=network.target` are necessary to make it start before systemd-networkd.

```diff
--- odroid-auto-bridge.service.orig     2018-02-09 21:50:06.535198446 +0100
+++ odroid-auto-bridge.service  2018-02-09 21:49:17.310078402 +0100
@@ -1,6 +1,7 @@
 [Unit]
 Description=call iproute2 to make a bridge
-Before=network.target
+Before=network-pre.target
+Wants=network-pre.target
 
 [Service]
 Type=oneshot
@@ -9,4 +10,4 @@
 ExecStop=/usr/bin/odroid-auto-bridge d
 
 [Install]
-WantedBy=default.target
+WantedBy=network.target
```

Without that there's no strict order for it to load necessarily before the network service since both odroid-auto-bridge.service and systemd-networkd.service are to be started before the network.target. So it's down to luck/race conditions when it gets loaded. It think doing it like in the diff makes it more universal and correct.

**Comment by graysky2** [comment]
If those changes work on your machine, I can verify that they also work on my C2.  I rebased the commit.  Thanks for the consideration.
